CREATE TYPE "EstadoGeneral" AS ENUM ('ACTIVO','INACTIVO','ARCHIVADO');
CREATE TYPE "EstadoClase" AS ENUM ('BORRADOR','PENDIENTE_APROBACION','PROGRAMADA','CONFIRMADA','EN_EJECUCION','EJECUTADA','REPROGRAMADA','CANCELADA','OBSERVADA');
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE "organizaciones" ("id" UUID PRIMARY KEY,"nombre" TEXT NOT NULL,"codigo" TEXT NOT NULL UNIQUE,"created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),"updated_at" TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE "usuarios" ("id" UUID PRIMARY KEY,"organizacion_id" UUID NOT NULL REFERENCES "organizaciones","nombre" TEXT NOT NULL,"correo" TEXT NOT NULL,"password_hash" TEXT NOT NULL,"estado" "EstadoGeneral" NOT NULL DEFAULT 'ACTIVO',"ultimo_acceso" TIMESTAMPTZ,"intentos_fallidos" INT NOT NULL DEFAULT 0,"created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),"updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),"deleted_at" TIMESTAMPTZ,"version" INT NOT NULL DEFAULT 1,UNIQUE("organizacion_id","correo"));
CREATE TABLE "roles" ("id" UUID PRIMARY KEY,"nombre" TEXT NOT NULL UNIQUE);
CREATE TABLE "permisos" ("id" UUID PRIMARY KEY,"codigo" TEXT NOT NULL UNIQUE,"descripcion" TEXT NOT NULL);
CREATE TABLE "usuarios_roles" ("usuario_id" UUID REFERENCES "usuarios" ON DELETE CASCADE,"rol_id" UUID REFERENCES "roles" ON DELETE CASCADE,PRIMARY KEY("usuario_id","rol_id"));
CREATE TABLE "roles_permisos" ("rol_id" UUID REFERENCES "roles" ON DELETE CASCADE,"permiso_id" UUID REFERENCES "permisos" ON DELETE CASCADE,PRIMARY KEY("rol_id","permiso_id"));
CREATE TABLE "programas" ("id" UUID PRIMARY KEY,"organizacion_id" UUID NOT NULL REFERENCES "organizaciones","codigo" TEXT NOT NULL,"nombre" TEXT NOT NULL,"descripcion" TEXT,"estado" "EstadoGeneral" NOT NULL DEFAULT 'ACTIVO',"created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),"updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),"deleted_at" TIMESTAMPTZ,"version" INT NOT NULL DEFAULT 1,UNIQUE("organizacion_id","codigo"));
CREATE TABLE "grupos" ("id" UUID PRIMARY KEY,"organizacion_id" UUID NOT NULL REFERENCES "organizaciones","programa_id" UUID NOT NULL REFERENCES "programas","codigo" TEXT NOT NULL,"fecha_inicio" DATE NOT NULL,"fecha_fin" DATE NOT NULL,"capacidad" INT NOT NULL CHECK("capacidad">0),"estado" "EstadoGeneral" NOT NULL DEFAULT 'ACTIVO',UNIQUE("organizacion_id","codigo"));
CREATE TABLE "docentes" ("id" UUID PRIMARY KEY,"organizacion_id" UUID NOT NULL REFERENCES "organizaciones","documento" TEXT NOT NULL,"nombres" TEXT NOT NULL,"apellidos" TEXT NOT NULL,"correo" TEXT NOT NULL,"horas_maximas_semana" INT NOT NULL DEFAULT 20,"estado" "EstadoGeneral" NOT NULL DEFAULT 'ACTIVO',UNIQUE("organizacion_id","documento"),UNIQUE("organizacion_id","correo"));
CREATE TABLE "estudiantes" ("id" UUID PRIMARY KEY,"organizacion_id" UUID NOT NULL REFERENCES "organizaciones","documento" TEXT NOT NULL,"nombres" TEXT NOT NULL,"apellidos" TEXT NOT NULL,"correo" TEXT NOT NULL,"telefono" TEXT,"estado" "EstadoGeneral" NOT NULL DEFAULT 'ACTIVO',"deleted_at" TIMESTAMPTZ,UNIQUE("organizacion_id","documento"),UNIQUE("organizacion_id","correo"));
CREATE TABLE "estudiantes_grupos" ("estudiante_id" UUID REFERENCES "estudiantes","grupo_id" UUID REFERENCES "grupos","fecha_ingreso" TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY("estudiante_id","grupo_id"));
CREATE TABLE "clases" ("id" UUID PRIMARY KEY,"grupo_id" UUID NOT NULL REFERENCES "grupos","docente_id" UUID NOT NULL REFERENCES "docentes","modulo_codigo" TEXT NOT NULL,"tema_codigo" TEXT NOT NULL,"titulo" TEXT NOT NULL,"inicio" TIMESTAMPTZ NOT NULL,"fin" TIMESTAMPTZ NOT NULL,"estado" "EstadoClase" NOT NULL DEFAULT 'BORRADOR',"tipo_repeticion" TEXT,"justificacion" TEXT,CHECK("fin">"inicio"));
CREATE TABLE "historial_clases" ("id" UUID PRIMARY KEY,"clase_id" UUID NOT NULL REFERENCES "clases","accion" TEXT NOT NULL,"motivo" TEXT,"anterior" JSONB,"nuevo" JSONB NOT NULL,"actor_id" UUID NOT NULL,"created_at" TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE "auditoria" ("id" UUID PRIMARY KEY,"usuario_id" UUID REFERENCES "usuarios","accion" TEXT NOT NULL,"entidad" TEXT NOT NULL,"entidad_id" TEXT NOT NULL,"anterior" JSONB,"nuevo" JSONB,"motivo" TEXT,"modulo" TEXT NOT NULL,"ip" TEXT,"correlacion" TEXT NOT NULL,"created_at" TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX ON "clases"("docente_id","inicio","fin"); CREATE INDEX ON "clases"("grupo_id","inicio","fin"); CREATE INDEX ON "clases"("grupo_id","modulo_codigo","tema_codigo"); CREATE INDEX ON "auditoria"("entidad","entidad_id"); CREATE INDEX ON "auditoria"("created_at");
